name: Build Sphinx Books

on: [workflow_dispatch]

defaults:
  run:
    working-directory: sphinx

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      LANG: uk_UA.UTF-8

    steps:
    - uses: actions/checkout@v4
    - name: Generate uk_UA locale
      run: |
          sudo sed -i -e '/uk_UA.UTF-8/s/# //' /etc/locale.gen
          sudo locale-gen
          locale -a
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: actions/checkout@v4
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Webpack & Sphinx production
      run: make html
    - name: Upload to page artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: sphinx/_build/html

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
